// Mocks generated by Mockito 5.4.6 from annotations
// in runaway/test/unit/mocks/mock_generator.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:typed_data' as _i17;
import 'dart:ui' as _i18;

import 'package:flutter/foundation.dart' as _i15;
import 'package:flutter_bloc/flutter_bloc.dart' as _i13;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i6;
import 'package:mapbox_maps_flutter/mapbox_maps_flutter.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:runaway/core/blocs/app_data/app_data_bloc.dart' as _i11;
import 'package:runaway/core/blocs/app_data/app_data_event.dart' as _i12;
import 'package:runaway/core/blocs/app_data/app_data_state.dart' as _i5;
import 'package:runaway/core/helper/services/connectivity_service.dart' as _i19;
import 'package:runaway/features/credits/data/services/credit_verification_service.dart'
    as _i4;
import 'package:runaway/features/route_generator/data/repositories/routes_repository.dart'
    as _i8;
import 'package:runaway/features/route_generator/data/services/graphhopper_api_service.dart'
    as _i14;
import 'package:runaway/features/route_generator/data/services/route_cache.dart'
    as _i3;
import 'package:runaway/features/route_generator/data/services/screenshot_service.dart'
    as _i20;
import 'package:runaway/features/route_generator/domain/models/route_parameters.dart'
    as _i10;
import 'package:runaway/features/route_generator/domain/models/saved_route.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSavedRoute_0 extends _i1.SmartFake implements _i2.SavedRoute {
  _FakeSavedRoute_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteCacheStats_1 extends _i1.SmartFake
    implements _i3.RouteCacheStats {
  _FakeRouteCacheStats_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreditVerificationResult_2 extends _i1.SmartFake
    implements _i4.CreditVerificationResult {
  _FakeCreditVerificationResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreditConsumptionResult_3 extends _i1.SmartFake
    implements _i4.CreditConsumptionResult {
  _FakeCreditConsumptionResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppDataState_4 extends _i1.SmartFake implements _i5.AppDataState {
  _FakeAppDataState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_5 extends _i1.SmartFake implements _i6.IOSOptions {
  _FakeIOSOptions_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_6 extends _i1.SmartFake
    implements _i6.AndroidOptions {
  _FakeAndroidOptions_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_7 extends _i1.SmartFake implements _i6.LinuxOptions {
  _FakeLinuxOptions_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_8 extends _i1.SmartFake
    implements _i6.WindowsOptions {
  _FakeWindowsOptions_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_9 extends _i1.SmartFake implements _i6.WebOptions {
  _FakeWebOptions_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsOptions_10 extends _i1.SmartFake implements _i6.MacOsOptions {
  _FakeMacOsOptions_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStyleManager_11 extends _i1.SmartFake implements _i7.StyleManager {
  _FakeStyleManager_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocationSettings_12 extends _i1.SmartFake
    implements _i7.LocationSettings {
  _FakeLocationSettings_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAnnotationManager_13 extends _i1.SmartFake
    implements _i7.AnnotationManager {
  _FakeAnnotationManager_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProjection_14 extends _i1.SmartFake implements _i7.Projection {
  _FakeProjection_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGesturesSettingsInterface_15 extends _i1.SmartFake
    implements _i7.GesturesSettingsInterface {
  _FakeGesturesSettingsInterface_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogoSettingsInterface_16 extends _i1.SmartFake
    implements _i7.LogoSettingsInterface {
  _FakeLogoSettingsInterface_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCompassSettingsInterface_17 extends _i1.SmartFake
    implements _i7.CompassSettingsInterface {
  _FakeCompassSettingsInterface_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeScaleBarSettingsInterface_18 extends _i1.SmartFake
    implements _i7.ScaleBarSettingsInterface {
  _FakeScaleBarSettingsInterface_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAttributionSettingsInterface_19 extends _i1.SmartFake
    implements _i7.AttributionSettingsInterface {
  _FakeAttributionSettingsInterface_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeMapboxHttpService_20 extends _i1.SmartFake
    implements _i7.MapboxHttpService {
  _FakeMapboxHttpService_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCameraOptions_21 extends _i1.SmartFake implements _i7.CameraOptions {
  _FakeCameraOptions_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCoordinateBounds_22 extends _i1.SmartFake
    implements _i7.CoordinateBounds {
  _FakeCoordinateBounds_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCoordinateBoundsZoom_23 extends _i1.SmartFake
    implements _i7.CoordinateBoundsZoom {
  _FakeCoordinateBoundsZoom_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeScreenCoordinate_24 extends _i1.SmartFake
    implements _i7.ScreenCoordinate {
  _FakeScreenCoordinate_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCameraState_25 extends _i1.SmartFake implements _i7.CameraState {
  _FakeCameraState_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCameraBounds_26 extends _i1.SmartFake implements _i7.CameraBounds {
  _FakeCameraBounds_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSize_27 extends _i1.SmartFake implements _i7.Size {
  _FakeSize_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMapOptions_28 extends _i1.SmartFake implements _i7.MapOptions {
  _FakeMapOptions_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFeatureExtensionValue_29 extends _i1.SmartFake
    implements _i7.FeatureExtensionValue {
  _FakeFeatureExtensionValue_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RoutesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoutesRepository extends _i1.Mock implements _i8.RoutesRepository {
  MockRoutesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.SavedRoute> saveRoute({
    required String? name,
    required _i10.RouteParameters? parameters,
    required List<List<double>>? coordinates,
    double? actualDistance,
    int? estimatedDuration,
    String? imageUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveRoute, [], {
              #name: name,
              #parameters: parameters,
              #coordinates: coordinates,
              #actualDistance: actualDistance,
              #estimatedDuration: estimatedDuration,
              #imageUrl: imageUrl,
            }),
            returnValue: _i9.Future<_i2.SavedRoute>.value(
              _FakeSavedRoute_0(
                this,
                Invocation.method(#saveRoute, [], {
                  #name: name,
                  #parameters: parameters,
                  #coordinates: coordinates,
                  #actualDistance: actualDistance,
                  #estimatedDuration: estimatedDuration,
                  #imageUrl: imageUrl,
                }),
              ),
            ),
          )
          as _i9.Future<_i2.SavedRoute>);

  @override
  _i9.Future<List<_i2.SavedRoute>> getUserRoutes({
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserRoutes, [], {
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i9.Future<List<_i2.SavedRoute>>.value(
              <_i2.SavedRoute>[],
            ),
          )
          as _i9.Future<List<_i2.SavedRoute>>);

  @override
  _i9.Future<void> deleteRoute(String? routeId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRoute, [routeId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> renameRoute(String? routeId, String? newName) =>
      (super.noSuchMethod(
            Invocation.method(#renameRoute, [routeId, newName]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateRouteUsage(String? routeId) =>
      (super.noSuchMethod(
            Invocation.method(#updateRouteUsage, [routeId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> syncPendingRoutes() =>
      (super.noSuchMethod(
            Invocation.method(#syncPendingRoutes, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> performMaintenanceTasks() =>
      (super.noSuchMethod(
            Invocation.method(#performMaintenanceTasks, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<Map<String, dynamic>> getSystemStats() =>
      (super.noSuchMethod(
            Invocation.method(#getSystemStats, []),
            returnValue: _i9.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<_i3.RouteCacheStats> getCacheStats() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheStats, []),
            returnValue: _i9.Future<_i3.RouteCacheStats>.value(
              _FakeRouteCacheStats_1(
                this,
                Invocation.method(#getCacheStats, []),
              ),
            ),
          )
          as _i9.Future<_i3.RouteCacheStats>);
}

/// A class which mocks [CreditVerificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreditVerificationService extends _i1.Mock
    implements _i4.CreditVerificationService {
  MockCreditVerificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i4.CreditVerificationResult> verifyCreditsForGeneration({
    int? requiredCredits = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyCreditsForGeneration, [], {
              #requiredCredits: requiredCredits,
            }),
            returnValue: _i9.Future<_i4.CreditVerificationResult>.value(
              _FakeCreditVerificationResult_2(
                this,
                Invocation.method(#verifyCreditsForGeneration, [], {
                  #requiredCredits: requiredCredits,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.CreditVerificationResult>);

  @override
  _i9.Future<_i4.CreditConsumptionResult> consumeCreditsForGeneration({
    required int? amount,
    required String? generationId,
    required Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#consumeCreditsForGeneration, [], {
              #amount: amount,
              #generationId: generationId,
              #metadata: metadata,
            }),
            returnValue: _i9.Future<_i4.CreditConsumptionResult>.value(
              _FakeCreditConsumptionResult_3(
                this,
                Invocation.method(#consumeCreditsForGeneration, [], {
                  #amount: amount,
                  #generationId: generationId,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.CreditConsumptionResult>);

  @override
  _i9.Future<bool> canGenerateRoute() =>
      (super.noSuchMethod(
            Invocation.method(#canGenerateRoute, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<int> getAvailableCredits() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableCredits, []),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  void ensureCreditDataLoaded() => super.noSuchMethod(
    Invocation.method(#ensureCreditDataLoaded, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AppDataBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDataBloc extends _i1.Mock implements _i11.AppDataBloc {
  MockAppDataBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isDataReady =>
      (super.noSuchMethod(Invocation.getter(#isDataReady), returnValue: false)
          as bool);

  @override
  _i5.AppDataState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAppDataState_4(this, Invocation.getter(#state)),
          )
          as _i5.AppDataState);

  @override
  _i9.Stream<_i5.AppDataState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<_i5.AppDataState>.empty(),
          )
          as _i9.Stream<_i5.AppDataState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i12.AppDataEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i12.AppDataEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i5.AppDataState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i12.AppDataEvent>(
    _i13.EventHandler<E, _i5.AppDataState>? handler, {
    _i13.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i13.Transition<_i12.AppDataEvent, _i5.AppDataState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void onChange(_i13.Change<_i5.AppDataState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GraphHopperApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphHopperApiService extends _i1.Mock
    implements _i14.GraphHopperApiService {
  MockGraphHopperApiService() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i6.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_5(this, Invocation.getter(#iOptions)),
          )
          as _i6.IOSOptions);

  @override
  _i6.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_6(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i6.AndroidOptions);

  @override
  _i6.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_7(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i6.LinuxOptions);

  @override
  _i6.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_8(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i6.WindowsOptions);

  @override
  _i6.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_9(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i6.WebOptions);

  @override
  _i6.MacOsOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeMacOsOptions_10(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i6.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i15.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i15.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> write({
    required String? key,
    required String? value,
    _i6.IOSOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.MacOsOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String?> read({
    required String? key,
    _i6.IOSOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.MacOsOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<bool> containsKey({
    required String? key,
    _i6.IOSOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.MacOsOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> delete({
    required String? key,
    _i6.IOSOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.MacOsOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<Map<String, String>> readAll({
    _i6.IOSOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.MacOsOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i9.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i9.Future<Map<String, String>>);

  @override
  _i9.Future<void> deleteAll({
    _i6.IOSOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.MacOsOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i9.Future<bool?>.value(),
          )
          as _i9.Future<bool?>);
}

/// A class which mocks [MapboxMap].
///
/// See the documentation for Mockito's code generation for more information.
class MockMapboxMap extends _i1.Mock implements _i7.MapboxMap {
  MockMapboxMap() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.StyleManager get style =>
      (super.noSuchMethod(
            Invocation.getter(#style),
            returnValue: _FakeStyleManager_11(this, Invocation.getter(#style)),
          )
          as _i7.StyleManager);

  @override
  _i7.LocationSettings get location =>
      (super.noSuchMethod(
            Invocation.getter(#location),
            returnValue: _FakeLocationSettings_12(
              this,
              Invocation.getter(#location),
            ),
          )
          as _i7.LocationSettings);

  @override
  _i7.AnnotationManager get annotations =>
      (super.noSuchMethod(
            Invocation.getter(#annotations),
            returnValue: _FakeAnnotationManager_13(
              this,
              Invocation.getter(#annotations),
            ),
          )
          as _i7.AnnotationManager);

  @override
  _i7.Projection get projection =>
      (super.noSuchMethod(
            Invocation.getter(#projection),
            returnValue: _FakeProjection_14(
              this,
              Invocation.getter(#projection),
            ),
          )
          as _i7.Projection);

  @override
  _i7.GesturesSettingsInterface get gestures =>
      (super.noSuchMethod(
            Invocation.getter(#gestures),
            returnValue: _FakeGesturesSettingsInterface_15(
              this,
              Invocation.getter(#gestures),
            ),
          )
          as _i7.GesturesSettingsInterface);

  @override
  _i7.LogoSettingsInterface get logo =>
      (super.noSuchMethod(
            Invocation.getter(#logo),
            returnValue: _FakeLogoSettingsInterface_16(
              this,
              Invocation.getter(#logo),
            ),
          )
          as _i7.LogoSettingsInterface);

  @override
  _i7.CompassSettingsInterface get compass =>
      (super.noSuchMethod(
            Invocation.getter(#compass),
            returnValue: _FakeCompassSettingsInterface_17(
              this,
              Invocation.getter(#compass),
            ),
          )
          as _i7.CompassSettingsInterface);

  @override
  _i7.ScaleBarSettingsInterface get scaleBar =>
      (super.noSuchMethod(
            Invocation.getter(#scaleBar),
            returnValue: _FakeScaleBarSettingsInterface_18(
              this,
              Invocation.getter(#scaleBar),
            ),
          )
          as _i7.ScaleBarSettingsInterface);

  @override
  _i7.AttributionSettingsInterface get attribution =>
      (super.noSuchMethod(
            Invocation.getter(#attribution),
            returnValue: _FakeAttributionSettingsInterface_19(
              this,
              Invocation.getter(#attribution),
            ),
          )
          as _i7.AttributionSettingsInterface);

  @override
  _i7.MapboxHttpService get httpService =>
      (super.noSuchMethod(
            Invocation.getter(#httpService),
            returnValue: _FakeMapboxHttpService_20(
              this,
              Invocation.getter(#httpService),
            ),
          )
          as _i7.MapboxHttpService);

  @override
  set annotations(_i7.AnnotationManager? _annotations) => super.noSuchMethod(
    Invocation.setter(#annotations, _annotations),
    returnValueForMissingStub: null,
  );

  @override
  set onMapTapListener(_i7.OnMapTapListener? _onMapTapListener) =>
      super.noSuchMethod(
        Invocation.setter(#onMapTapListener, _onMapTapListener),
        returnValueForMissingStub: null,
      );

  @override
  set onMapLongTapListener(_i7.OnMapLongTapListener? _onMapLongTapListener) =>
      super.noSuchMethod(
        Invocation.setter(#onMapLongTapListener, _onMapLongTapListener),
        returnValueForMissingStub: null,
      );

  @override
  set onMapScrollListener(_i7.OnMapScrollListener? _onMapScrollListener) =>
      super.noSuchMethod(
        Invocation.setter(#onMapScrollListener, _onMapScrollListener),
        returnValueForMissingStub: null,
      );

  @override
  set onMapZoomListener(_i7.OnMapZoomListener? _onMapZoomListener) =>
      super.noSuchMethod(
        Invocation.setter(#onMapZoomListener, _onMapZoomListener),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<_i7.CameraOptions> cameraForCoordinatesPadding(
    List<_i7.Point>? coordinates,
    _i7.CameraOptions? camera,
    _i7.MbxEdgeInsets? coordinatesPadding,
    double? maxZoom,
    _i7.ScreenCoordinate? offset,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cameraForCoordinatesPadding, [
              coordinates,
              camera,
              coordinatesPadding,
              maxZoom,
              offset,
            ]),
            returnValue: _i9.Future<_i7.CameraOptions>.value(
              _FakeCameraOptions_21(
                this,
                Invocation.method(#cameraForCoordinatesPadding, [
                  coordinates,
                  camera,
                  coordinatesPadding,
                  maxZoom,
                  offset,
                ]),
              ),
            ),
          )
          as _i9.Future<_i7.CameraOptions>);

  @override
  _i9.Future<_i7.CameraOptions> cameraForCoordinateBounds(
    _i7.CoordinateBounds? bounds,
    _i7.MbxEdgeInsets? padding,
    double? bearing,
    double? pitch,
    double? maxZoom,
    _i7.ScreenCoordinate? offset,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cameraForCoordinateBounds, [
              bounds,
              padding,
              bearing,
              pitch,
              maxZoom,
              offset,
            ]),
            returnValue: _i9.Future<_i7.CameraOptions>.value(
              _FakeCameraOptions_21(
                this,
                Invocation.method(#cameraForCoordinateBounds, [
                  bounds,
                  padding,
                  bearing,
                  pitch,
                  maxZoom,
                  offset,
                ]),
              ),
            ),
          )
          as _i9.Future<_i7.CameraOptions>);

  @override
  _i9.Future<_i7.CameraOptions> cameraForCoordinates(
    List<_i7.Point>? coordinates,
    _i7.MbxEdgeInsets? padding,
    double? bearing,
    double? pitch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cameraForCoordinates, [
              coordinates,
              padding,
              bearing,
              pitch,
            ]),
            returnValue: _i9.Future<_i7.CameraOptions>.value(
              _FakeCameraOptions_21(
                this,
                Invocation.method(#cameraForCoordinates, [
                  coordinates,
                  padding,
                  bearing,
                  pitch,
                ]),
              ),
            ),
          )
          as _i9.Future<_i7.CameraOptions>);

  @override
  _i9.Future<_i7.CameraOptions> cameraForCoordinatesCameraOptions(
    List<_i7.Point>? coordinates,
    _i7.CameraOptions? camera,
    _i7.ScreenBox? box,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cameraForCoordinatesCameraOptions, [
              coordinates,
              camera,
              box,
            ]),
            returnValue: _i9.Future<_i7.CameraOptions>.value(
              _FakeCameraOptions_21(
                this,
                Invocation.method(#cameraForCoordinatesCameraOptions, [
                  coordinates,
                  camera,
                  box,
                ]),
              ),
            ),
          )
          as _i9.Future<_i7.CameraOptions>);

  @override
  _i9.Future<_i7.CameraOptions> cameraForGeometry(
    Map<String?, Object?>? geometry,
    _i7.MbxEdgeInsets? padding,
    double? bearing,
    double? pitch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cameraForGeometry, [
              geometry,
              padding,
              bearing,
              pitch,
            ]),
            returnValue: _i9.Future<_i7.CameraOptions>.value(
              _FakeCameraOptions_21(
                this,
                Invocation.method(#cameraForGeometry, [
                  geometry,
                  padding,
                  bearing,
                  pitch,
                ]),
              ),
            ),
          )
          as _i9.Future<_i7.CameraOptions>);

  @override
  _i9.Future<_i7.CoordinateBounds> coordinateBoundsForCamera(
    _i7.CameraOptions? camera,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#coordinateBoundsForCamera, [camera]),
            returnValue: _i9.Future<_i7.CoordinateBounds>.value(
              _FakeCoordinateBounds_22(
                this,
                Invocation.method(#coordinateBoundsForCamera, [camera]),
              ),
            ),
          )
          as _i9.Future<_i7.CoordinateBounds>);

  @override
  _i9.Future<_i7.CoordinateBounds> coordinateBoundsForCameraUnwrapped(
    _i7.CameraOptions? camera,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#coordinateBoundsForCameraUnwrapped, [camera]),
            returnValue: _i9.Future<_i7.CoordinateBounds>.value(
              _FakeCoordinateBounds_22(
                this,
                Invocation.method(#coordinateBoundsForCameraUnwrapped, [
                  camera,
                ]),
              ),
            ),
          )
          as _i9.Future<_i7.CoordinateBounds>);

  @override
  _i9.Future<_i7.CoordinateBoundsZoom> coordinateBoundsZoomForCamera(
    _i7.CameraOptions? camera,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#coordinateBoundsZoomForCamera, [camera]),
            returnValue: _i9.Future<_i7.CoordinateBoundsZoom>.value(
              _FakeCoordinateBoundsZoom_23(
                this,
                Invocation.method(#coordinateBoundsZoomForCamera, [camera]),
              ),
            ),
          )
          as _i9.Future<_i7.CoordinateBoundsZoom>);

  @override
  _i9.Future<_i7.CoordinateBoundsZoom> coordinateBoundsZoomForCameraUnwrapped(
    _i7.CameraOptions? camera,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#coordinateBoundsZoomForCameraUnwrapped, [
              camera,
            ]),
            returnValue: _i9.Future<_i7.CoordinateBoundsZoom>.value(
              _FakeCoordinateBoundsZoom_23(
                this,
                Invocation.method(#coordinateBoundsZoomForCameraUnwrapped, [
                  camera,
                ]),
              ),
            ),
          )
          as _i9.Future<_i7.CoordinateBoundsZoom>);

  @override
  _i9.Future<_i7.ScreenCoordinate> pixelForCoordinate(_i7.Point? coordinate) =>
      (super.noSuchMethod(
            Invocation.method(#pixelForCoordinate, [coordinate]),
            returnValue: _i9.Future<_i7.ScreenCoordinate>.value(
              _FakeScreenCoordinate_24(
                this,
                Invocation.method(#pixelForCoordinate, [coordinate]),
              ),
            ),
          )
          as _i9.Future<_i7.ScreenCoordinate>);

  @override
  _i9.Future<_i7.Point> coordinateForPixel(_i7.ScreenCoordinate? pixel) =>
      (super.noSuchMethod(
            Invocation.method(#coordinateForPixel, [pixel]),
            returnValue: _i9.Future<_i7.Point>.value(
              _i16.dummyValue<_i7.Point>(
                this,
                Invocation.method(#coordinateForPixel, [pixel]),
              ),
            ),
          )
          as _i9.Future<_i7.Point>);

  @override
  _i9.Future<List<_i7.ScreenCoordinate?>> pixelsForCoordinates(
    List<_i7.Point>? coordinates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#pixelsForCoordinates, [coordinates]),
            returnValue: _i9.Future<List<_i7.ScreenCoordinate?>>.value(
              <_i7.ScreenCoordinate?>[],
            ),
          )
          as _i9.Future<List<_i7.ScreenCoordinate?>>);

  @override
  _i9.Future<List<_i7.Point?>> coordinatesForPixels(
    List<_i7.ScreenCoordinate?>? pixels,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#coordinatesForPixels, [pixels]),
            returnValue: _i9.Future<List<_i7.Point?>>.value(<_i7.Point?>[]),
          )
          as _i9.Future<List<_i7.Point?>>);

  @override
  _i9.Future<void> setCamera(_i7.CameraOptions? cameraOptions) =>
      (super.noSuchMethod(
            Invocation.method(#setCamera, [cameraOptions]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i7.CameraState> getCameraState() =>
      (super.noSuchMethod(
            Invocation.method(#getCameraState, []),
            returnValue: _i9.Future<_i7.CameraState>.value(
              _FakeCameraState_25(this, Invocation.method(#getCameraState, [])),
            ),
          )
          as _i9.Future<_i7.CameraState>);

  @override
  _i9.Future<void> setBounds(_i7.CameraBoundsOptions? options) =>
      (super.noSuchMethod(
            Invocation.method(#setBounds, [options]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i7.CameraBounds> getBounds() =>
      (super.noSuchMethod(
            Invocation.method(#getBounds, []),
            returnValue: _i9.Future<_i7.CameraBounds>.value(
              _FakeCameraBounds_26(this, Invocation.method(#getBounds, [])),
            ),
          )
          as _i9.Future<_i7.CameraBounds>);

  @override
  _i9.Future<_i7.Size> getSize() =>
      (super.noSuchMethod(
            Invocation.method(#getSize, []),
            returnValue: _i9.Future<_i7.Size>.value(
              _FakeSize_27(this, Invocation.method(#getSize, [])),
            ),
          )
          as _i9.Future<_i7.Size>);

  @override
  _i9.Future<void> triggerRepaint() =>
      (super.noSuchMethod(
            Invocation.method(#triggerRepaint, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setGestureInProgress(bool? inProgress) =>
      (super.noSuchMethod(
            Invocation.method(#setGestureInProgress, [inProgress]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<bool> isGestureInProgress() =>
      (super.noSuchMethod(
            Invocation.method(#isGestureInProgress, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> dispatch(
    String? gesture,
    _i7.ScreenCoordinate? screenCoordinate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#dispatch, [gesture, screenCoordinate]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setUserAnimationInProgress(bool? inProgress) =>
      (super.noSuchMethod(
            Invocation.method(#setUserAnimationInProgress, [inProgress]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<bool> isUserAnimationInProgress() =>
      (super.noSuchMethod(
            Invocation.method(#isUserAnimationInProgress, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> setPrefetchZoomDelta(int? delta) =>
      (super.noSuchMethod(
            Invocation.method(#setPrefetchZoomDelta, [delta]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<int> getPrefetchZoomDelta() =>
      (super.noSuchMethod(
            Invocation.method(#getPrefetchZoomDelta, []),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<void> setNorthOrientation(_i7.NorthOrientation? orientation) =>
      (super.noSuchMethod(
            Invocation.method(#setNorthOrientation, [orientation]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setConstrainMode(_i7.ConstrainMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setConstrainMode, [mode]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setViewportMode(_i7.ViewportMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setViewportMode, [mode]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i7.MapOptions> getMapOptions() =>
      (super.noSuchMethod(
            Invocation.method(#getMapOptions, []),
            returnValue: _i9.Future<_i7.MapOptions>.value(
              _FakeMapOptions_28(this, Invocation.method(#getMapOptions, [])),
            ),
          )
          as _i9.Future<_i7.MapOptions>);

  @override
  _i9.Future<String> styleGlyphURL() =>
      (super.noSuchMethod(
            Invocation.method(#styleGlyphURL, []),
            returnValue: _i9.Future<String>.value(
              _i16.dummyValue<String>(
                this,
                Invocation.method(#styleGlyphURL, []),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> setStyleGlyphURL(String? glyphURL) =>
      (super.noSuchMethod(
            Invocation.method(#setStyleGlyphURL, [glyphURL]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i7.MapWidgetDebugOptions>> getDebugOptions() =>
      (super.noSuchMethod(
            Invocation.method(#getDebugOptions, []),
            returnValue: _i9.Future<List<_i7.MapWidgetDebugOptions>>.value(
              <_i7.MapWidgetDebugOptions>[],
            ),
          )
          as _i9.Future<List<_i7.MapWidgetDebugOptions>>);

  @override
  _i9.Future<void> setDebugOptions(
    List<_i7.MapWidgetDebugOptions>? debugOptions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setDebugOptions, [debugOptions]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i7.MapDebugOptions?>> getDebug() =>
      (super.noSuchMethod(
            Invocation.method(#getDebug, []),
            returnValue: _i9.Future<List<_i7.MapDebugOptions?>>.value(
              <_i7.MapDebugOptions?>[],
            ),
          )
          as _i9.Future<List<_i7.MapDebugOptions?>>);

  @override
  _i9.Future<void> setDebug(
    List<_i7.MapDebugOptions?>? debugOptions,
    bool? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setDebug, [debugOptions, value]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i7.QueriedRenderedFeature?>> queryRenderedFeatures(
    _i7.RenderedQueryGeometry? geometry,
    _i7.RenderedQueryOptions? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#queryRenderedFeatures, [geometry, options]),
            returnValue: _i9.Future<List<_i7.QueriedRenderedFeature?>>.value(
              <_i7.QueriedRenderedFeature?>[],
            ),
          )
          as _i9.Future<List<_i7.QueriedRenderedFeature?>>);

  @override
  _i9.Future<List<_i7.FeaturesetFeature>> queryRenderedFeaturesForFeatureset({
    required _i7.FeaturesetDescriptor? featureset,
    _i7.RenderedQueryGeometry? geometry,
    String? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#queryRenderedFeaturesForFeatureset, [], {
              #featureset: featureset,
              #geometry: geometry,
              #filter: filter,
            }),
            returnValue: _i9.Future<List<_i7.FeaturesetFeature>>.value(
              <_i7.FeaturesetFeature>[],
            ),
          )
          as _i9.Future<List<_i7.FeaturesetFeature>>);

  @override
  _i9.Future<List<_i7.QueriedSourceFeature?>> querySourceFeatures(
    String? sourceId,
    _i7.SourceQueryOptions? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#querySourceFeatures, [sourceId, options]),
            returnValue: _i9.Future<List<_i7.QueriedSourceFeature?>>.value(
              <_i7.QueriedSourceFeature?>[],
            ),
          )
          as _i9.Future<List<_i7.QueriedSourceFeature?>>);

  @override
  _i9.Future<_i7.FeatureExtensionValue> getGeoJsonClusterLeaves(
    String? sourceIdentifier,
    Map<String?, Object?>? cluster,
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGeoJsonClusterLeaves, [
              sourceIdentifier,
              cluster,
              limit,
              offset,
            ]),
            returnValue: _i9.Future<_i7.FeatureExtensionValue>.value(
              _FakeFeatureExtensionValue_29(
                this,
                Invocation.method(#getGeoJsonClusterLeaves, [
                  sourceIdentifier,
                  cluster,
                  limit,
                  offset,
                ]),
              ),
            ),
          )
          as _i9.Future<_i7.FeatureExtensionValue>);

  @override
  _i9.Future<_i7.FeatureExtensionValue> getGeoJsonClusterChildren(
    String? sourceIdentifier,
    Map<String?, Object?>? cluster,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGeoJsonClusterChildren, [
              sourceIdentifier,
              cluster,
            ]),
            returnValue: _i9.Future<_i7.FeatureExtensionValue>.value(
              _FakeFeatureExtensionValue_29(
                this,
                Invocation.method(#getGeoJsonClusterChildren, [
                  sourceIdentifier,
                  cluster,
                ]),
              ),
            ),
          )
          as _i9.Future<_i7.FeatureExtensionValue>);

  @override
  _i9.Future<_i7.FeatureExtensionValue> getGeoJsonClusterExpansionZoom(
    String? sourceIdentifier,
    Map<String?, Object?>? cluster,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGeoJsonClusterExpansionZoom, [
              sourceIdentifier,
              cluster,
            ]),
            returnValue: _i9.Future<_i7.FeatureExtensionValue>.value(
              _FakeFeatureExtensionValue_29(
                this,
                Invocation.method(#getGeoJsonClusterExpansionZoom, [
                  sourceIdentifier,
                  cluster,
                ]),
              ),
            ),
          )
          as _i9.Future<_i7.FeatureExtensionValue>);

  @override
  _i9.Future<void> setFeatureState(
    String? sourceId,
    String? sourceLayerId,
    String? featureId,
    String? state,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setFeatureState, [
              sourceId,
              sourceLayerId,
              featureId,
              state,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setFeatureStateForFeaturesetDescriptor(
    _i7.FeaturesetDescriptor? featureset,
    _i7.FeaturesetFeatureId? featureId,
    _i7.FeatureState? state,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setFeatureStateForFeaturesetDescriptor, [
              featureset,
              featureId,
              state,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setFeatureStateForFeaturesetFeature(
    _i7.FeaturesetFeature? feature,
    _i7.FeatureState? state,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setFeatureStateForFeaturesetFeature, [
              feature,
              state,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String> getFeatureState(
    String? sourceId,
    String? sourceLayerId,
    String? featureId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFeatureState, [
              sourceId,
              sourceLayerId,
              featureId,
            ]),
            returnValue: _i9.Future<String>.value(
              _i16.dummyValue<String>(
                this,
                Invocation.method(#getFeatureState, [
                  sourceId,
                  sourceLayerId,
                  featureId,
                ]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<Map<String, Object?>> getFeatureStateForFeaturesetDescriptor(
    _i7.FeaturesetDescriptor? featureset,
    _i7.FeaturesetFeatureId? featureId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFeatureStateForFeaturesetDescriptor, [
              featureset,
              featureId,
            ]),
            returnValue: _i9.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i9.Future<Map<String, Object?>>);

  @override
  _i9.Future<Map<String, Object?>> getFeatureStateForFeaturesetFeature(
    _i7.FeaturesetFeature? feature,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFeatureStateForFeaturesetFeature, [feature]),
            returnValue: _i9.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i9.Future<Map<String, Object?>>);

  @override
  _i9.Future<void> removeFeatureState(
    String? sourceId,
    String? sourceLayerId,
    String? featureId,
    String? stateKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeFeatureState, [
              sourceId,
              sourceLayerId,
              featureId,
              stateKey,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> removeFeatureStateForFeaturesetDescriptor({
    required _i7.FeaturesetDescriptor? featureset,
    required _i7.FeaturesetFeatureId? featureId,
    String? stateKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeFeatureStateForFeaturesetDescriptor, [], {
              #featureset: featureset,
              #featureId: featureId,
              #stateKey: stateKey,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> removeFeatureStateForFeaturesetFeature({
    required _i7.FeaturesetFeature? feature,
    String? stateKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeFeatureStateForFeaturesetFeature, [], {
              #feature: feature,
              #stateKey: stateKey,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> resetFeatureStatesForFeatureset(
    _i7.FeaturesetDescriptor? featureset,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetFeatureStatesForFeatureset, [featureset]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void addInteraction<
    T extends _i7.TypedFeaturesetFeature<_i7.FeaturesetDescriptor>
  >(_i7.TypedInteraction<T>? interaction, {String? interactionID}) =>
      super.noSuchMethod(
        Invocation.method(
          #addInteraction,
          [interaction],
          {#interactionID: interactionID},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeInteraction(String? interactionID) => super.noSuchMethod(
    Invocation.method(#removeInteraction, [interactionID]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> reduceMemoryUse() =>
      (super.noSuchMethod(
            Invocation.method(#reduceMemoryUse, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<double?> getElevation(_i7.Point? coordinate) =>
      (super.noSuchMethod(
            Invocation.method(#getElevation, [coordinate]),
            returnValue: _i9.Future<double?>.value(),
          )
          as _i9.Future<double?>);

  @override
  _i9.Future<void> loadStyleURI(String? styleURI) =>
      (super.noSuchMethod(
            Invocation.method(#loadStyleURI, [styleURI]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> loadStyleJson(String? styleJson) =>
      (super.noSuchMethod(
            Invocation.method(#loadStyleJson, [styleJson]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> clearData() =>
      (super.noSuchMethod(
            Invocation.method(#clearData, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setTileCacheBudget(
    _i7.TileCacheBudgetInMegabytes? tileCacheBudgetInMegabytes,
    _i7.TileCacheBudgetInTiles? tileCacheBudgetInTiles,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setTileCacheBudget, [
              tileCacheBudgetInMegabytes,
              tileCacheBudgetInTiles,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> easeTo(
    _i7.CameraOptions? cameraOptions,
    _i7.MapAnimationOptions? mapAnimationOptions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#easeTo, [cameraOptions, mapAnimationOptions]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> flyTo(
    _i7.CameraOptions? cameraOptions,
    _i7.MapAnimationOptions? mapAnimationOptions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#flyTo, [cameraOptions, mapAnimationOptions]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> pitchBy(
    double? pitch,
    _i7.MapAnimationOptions? mapAnimationOptions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#pitchBy, [pitch, mapAnimationOptions]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> scaleBy(
    double? amount,
    _i7.ScreenCoordinate? screenCoordinate,
    _i7.MapAnimationOptions? mapAnimationOptions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#scaleBy, [
              amount,
              screenCoordinate,
              mapAnimationOptions,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> moveBy(
    _i7.ScreenCoordinate? screenCoordinate,
    _i7.MapAnimationOptions? mapAnimationOptions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#moveBy, [screenCoordinate, mapAnimationOptions]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> rotateBy(
    _i7.ScreenCoordinate? first,
    _i7.ScreenCoordinate? second,
    _i7.MapAnimationOptions? mapAnimationOptions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#rotateBy, [first, second, mapAnimationOptions]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> cancelCameraAnimation() =>
      (super.noSuchMethod(
            Invocation.method(#cancelCameraAnimation, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void startPerformanceStatisticsCollection(
    _i7.PerformanceStatisticsOptions? options,
    _i7.PerformanceStatisticsListener? listener,
  ) => super.noSuchMethod(
    Invocation.method(#startPerformanceStatisticsCollection, [
      options,
      listener,
    ]),
    returnValueForMissingStub: null,
  );

  @override
  void stopPerformanceStatisticsCollection() => super.noSuchMethod(
    Invocation.method(#stopPerformanceStatisticsCollection, []),
    returnValueForMissingStub: null,
  );

  @override
  void setOnMapTapListener(_i7.OnMapTapListener? onMapTapListener) =>
      super.noSuchMethod(
        Invocation.method(#setOnMapTapListener, [onMapTapListener]),
        returnValueForMissingStub: null,
      );

  @override
  void setOnMapLongTapListener(
    _i7.OnMapLongTapListener? onMapLongTapListener,
  ) => super.noSuchMethod(
    Invocation.method(#setOnMapLongTapListener, [onMapLongTapListener]),
    returnValueForMissingStub: null,
  );

  @override
  void setOnMapMoveListener(_i7.OnMapScrollListener? onMapScrollListener) =>
      super.noSuchMethod(
        Invocation.method(#setOnMapMoveListener, [onMapScrollListener]),
        returnValueForMissingStub: null,
      );

  @override
  void setOnMapZoomListener(_i7.OnMapZoomListener? onMapZoomListener) =>
      super.noSuchMethod(
        Invocation.method(#setOnMapZoomListener, [onMapZoomListener]),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<_i17.Uint8List> snapshot() =>
      (super.noSuchMethod(
            Invocation.method(#snapshot, []),
            returnValue: _i9.Future<_i17.Uint8List>.value(_i17.Uint8List(0)),
          )
          as _i9.Future<_i17.Uint8List>);

  @override
  _i9.Future<void> setSnapshotLegacyMode(bool? enable) =>
      (super.noSuchMethod(
            Invocation.method(#setSnapshotLegacyMode, [enable]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setCustomHeaders(Map<String, String>? headers) =>
      (super.noSuchMethod(
            Invocation.method(#setCustomHeaders, [headers]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void addListener(_i18.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i18.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i19.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Stream<_i19.ConnectionStatus> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<_i19.ConnectionStatus>.empty(),
          )
          as _i9.Stream<_i19.ConnectionStatus>);

  @override
  _i19.ConnectionStatus get current =>
      (super.noSuchMethod(
            Invocation.getter(#current),
            returnValue: _i19.ConnectionStatus.onlineWifi,
          )
          as _i19.ConnectionStatus);

  @override
  bool get isOffline =>
      (super.noSuchMethod(Invocation.getter(#isOffline), returnValue: false)
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  _i9.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> forceCheck() =>
      (super.noSuchMethod(
            Invocation.method(#forceCheck, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i19.ConnectionStatus getCurrentSync() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentSync, []),
            returnValue: _i19.ConnectionStatus.onlineWifi,
          )
          as _i19.ConnectionStatus);

  @override
  bool canMakeNetworkCalls() =>
      (super.noSuchMethod(
            Invocation.method(#canMakeNetworkCalls, []),
            returnValue: false,
          )
          as bool);

  @override
  _i9.Future<void> waitForInitialization({
    Duration? timeout = const Duration(seconds: 3),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#waitForInitialization, [], {#timeout: timeout}),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ScreenshotService].
///
/// See the documentation for Mockito's code generation for more information.
class MockScreenshotService extends _i1.Mock implements _i20.IScreenshotService {
  MockScreenshotService() {
    _i1.throwOnMissingStub(this);
  }
}
