# docker-compose.yml
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: runaway-api
    ports:
      - "3001:3000"
    env_file:
      - .env  # Lire le fichier .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Ces variables seront lues depuis .env mais on peut aussi les forcer ici
      - GRAPHHOPPER_API_KEY=${GRAPHHOPPER_API_KEY}
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=info
      - ALLOWED_ORIGINS=http://localhost:3000,https://yourdomain.com
    volumes:
      - ../logs:/app/logs
    restart: unless-stopped
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:alpine
    container_name: runaway-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis-data: